<?php

namespace App\Providers;

class ACFFieldProvider
{
    public static function register(): void
    {
        static::registerFieldGroups();
    }

    public static function registerFieldGroups(): void
    {
        if (! \function_exists('acf_add_local_field_group')) {
            return;
        }

        if (\function_exists('acf_add_options_page')) {
            foreach (
                [
                    ['page_title' => 'Header/Footer PL', 'menu_title' => 'Header/Footer PL', 'menu_slug' => 'header-footer-pl', 'post_id' => 'header-footer-pl'],
                    ['page_title' => 'Header/Footer EN', 'menu_title' => 'Header/Footer EN', 'menu_slug' => 'header-footer-en', 'post_id' => 'header-footer-en'],
                    ['page_title' => 'Header/Footer FR', 'menu_title' => 'Header/Footer FR', 'menu_slug' => 'header-footer-fr', 'post_id' => 'header-footer-fr'],
                ] as $optionsPage
            ) {
                \acf_add_options_page($optionsPage + [
                    'capability' => 'edit_posts',
                    'redirect' => false,
                    'position' => 58,
                    'icon_url' => 'dashicons-admin-customizer',
                ]);
            }
        }

        \acf_add_local_field_group([
            'key' => 'group_front_page',
            'title' => 'Front Page',
            'fields' => [
                [
                    'key' => 'field_front_page_hero_tab',
                    'label' => 'Hero',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_front_hero_background_image',
                    'label' => 'Hero Background Image',
                    'name' => 'front_hero_background_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
                [
                    'key' => 'field_front_hero_arrow_text',
                    'label' => 'Hero Arrow Text',
                    'name' => 'front_hero_arrow_text',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_hero_eyebrow',
                    'label' => 'Hero Eyebrow',
                    'name' => 'front_hero_eyebrow',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_hero_title',
                    'label' => 'Hero Title',
                    'name' => 'front_hero_title',
                    'type' => 'textarea',
                    'rows' => 3,
                    'new_lines' => 'br',
                ],
                [
                    'key' => 'field_front_page_services_tab',
                    'label' => 'Services Navigation',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_front_services',
                    'label' => 'Services',
                    'name' => 'front_services',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Service',
                    'sub_fields' => [
                        [
                            'key' => 'field_front_services_number',
                            'label' => 'Number',
                            'name' => 'number',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_front_services_title',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_front_services_link',
                            'label' => 'Link',
                            'name' => 'link',
                            'type' => 'link',
                            'return_format' => 'array',
                        ],
                        [
                            'key' => 'field_front_services_read_more_label',
                            'label' => 'Read More Label',
                            'name' => 'read_more_label',
                            'type' => 'text',
                            'default_value' => 'Czytaj więcej',
                        ],
                    ],
                ],
                [
                    'key' => 'field_front_page_philosophy_tab',
                    'label' => 'Philosophy Teaser',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_front_philosophy_image',
                    'label' => 'Philosophy Image',
                    'name' => 'front_philosophy_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
                [
                    'key' => 'field_front_philosophy_arrow_text',
                    'label' => 'Philosophy Arrow Text',
                    'name' => 'front_philosophy_arrow_text',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_philosophy_title',
                    'label' => 'Philosophy Title',
                    'name' => 'front_philosophy_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_philosophy_text',
                    'label' => 'Philosophy Text',
                    'name' => 'front_philosophy_text',
                    'type' => 'wysiwyg',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                ],
                [
                    'key' => 'field_front_philosophy_button_label',
                    'label' => 'Philosophy Button Label',
                    'name' => 'front_philosophy_button_label',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_philosophy_button_link',
                    'label' => 'Philosophy Button Link',
                    'name' => 'front_philosophy_button_link',
                    'type' => 'link',
                    'return_format' => 'array',
                ],
                [
                    'key' => 'field_front_page_team_tab',
                    'label' => 'Team Teaser',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_front_team_title',
                    'label' => 'Team Title',
                    'name' => 'front_team_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_team_description',
                    'label' => 'Team Description',
                    'name' => 'front_team_description',
                    'type' => 'textarea',
                    'rows' => 4,
                    'new_lines' => 'br',
                ],
                [
                    'key' => 'field_front_team_button_label',
                    'label' => 'Team Button Label',
                    'name' => 'front_team_button_label',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_team_button_link',
                    'label' => 'Team Button Link',
                    'name' => 'front_team_button_link',
                    'type' => 'link',
                    'return_format' => 'array',
                ],
                [
                    'key' => 'field_front_team_featured_image',
                    'label' => 'Featured Team Image',
                    'name' => 'front_team_featured_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
                [
                    'key' => 'field_front_team_featured_name',
                    'label' => 'Featured Team Name',
                    'name' => 'front_team_featured_name',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_team_featured_position',
                    'label' => 'Featured Team Position',
                    'name' => 'front_team_featured_position',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_team_featured_description',
                    'label' => 'Featured Team Description',
                    'name' => 'front_team_featured_description',
                    'type' => 'textarea',
                    'rows' => 5,
                    'new_lines' => 'br',
                ],
                [
                    'key' => 'field_front_page_reviews_tab',
                    'label' => 'Google Reviews Teaser',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_front_reviews_title',
                    'label' => 'Reviews Title',
                    'name' => 'front_reviews_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_reviews_items',
                    'label' => 'Reviews',
                    'name' => 'front_reviews_items',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Review',
                    'sub_fields' => [
                        [
                            'key' => 'field_front_reviews_rating',
                            'label' => 'Rating',
                            'name' => 'rating',
                            'type' => 'number',
                            'min' => 1,
                            'max' => 5,
                            'step' => 1,
                        ],
                        [
                            'key' => 'field_front_reviews_text',
                            'label' => 'Text',
                            'name' => 'text',
                            'type' => 'textarea',
                            'rows' => 4,
                            'new_lines' => 'br',
                        ],
                        [
                            'key' => 'field_front_reviews_author',
                            'label' => 'Author',
                            'name' => 'author',
                            'type' => 'text',
                        ],
                    ],
                ],
                [
                    'key' => 'field_front_page_faq_tab',
                    'label' => 'FAQ Teaser',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_front_faq_title',
                    'label' => 'FAQ Title',
                    'name' => 'front_faq_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_faq_items',
                    'label' => 'FAQ Items',
                    'name' => 'front_faq_items',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add FAQ Item',
                    'sub_fields' => [
                        [
                            'key' => 'field_front_faq_question',
                            'label' => 'Question',
                            'name' => 'question',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_front_faq_answer',
                            'label' => 'Answer',
                            'name' => 'answer',
                            'type' => 'wysiwyg',
                            'tabs' => 'all',
                            'toolbar' => 'basic',
                            'media_upload' => 0,
                        ],
                    ],
                ],
                [
                    'key' => 'field_front_faq_button_label',
                    'label' => 'FAQ Button Label',
                    'name' => 'front_faq_button_label',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_faq_button_link',
                    'label' => 'FAQ Button Link',
                    'name' => 'front_faq_button_link',
                    'type' => 'link',
                    'return_format' => 'array',
                ],
                [
                    'key' => 'field_front_faq_image',
                    'label' => 'FAQ Image',
                    'name' => 'front_faq_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'page_type',
                        'operator' => '==',
                        'value' => 'front_page',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ]);

        \acf_add_local_field_group([
            'key' => 'group_about_us_page',
            'title' => 'About Us Page',
            'fields' => [
                [
                    'key' => 'field_about_page_breadcrumbs_tab',
                    'label' => 'Breadcrumbs',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_breadcrumb_items',
                    'label' => 'Breadcrumb Items',
                    'name' => 'about_breadcrumb_items',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Breadcrumb',
                    'sub_fields' => [
                        [
                            'key' => 'field_about_breadcrumb_item_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_about_breadcrumb_item_link',
                            'label' => 'Link',
                            'name' => 'link',
                            'type' => 'link',
                            'return_format' => 'array',
                        ],
                    ],
                ],
                [
                    'key' => 'field_about_page_philosophy_tab',
                    'label' => 'Philosophy Section',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_philosophy_title',
                    'label' => 'Philosophy Title',
                    'name' => 'about_philosophy_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_about_philosophy_content',
                    'label' => 'Philosophy Content',
                    'name' => 'about_philosophy_content',
                    'type' => 'wysiwyg',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                ],
                [
                    'key' => 'field_about_philosophy_image',
                    'label' => 'Philosophy Image',
                    'name' => 'about_philosophy_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
                [
                    'key' => 'field_about_page_why_tab',
                    'label' => 'Why Us Section',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_why_image',
                    'label' => 'Why Us Image',
                    'name' => 'about_why_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
                [
                    'key' => 'field_about_why_title',
                    'label' => 'Why Us Title',
                    'name' => 'about_why_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_about_why_content',
                    'label' => 'Why Us Content',
                    'name' => 'about_why_content',
                    'type' => 'wysiwyg',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                ],
                [
                    'key' => 'field_about_page_team_tab',
                    'label' => 'Team Section',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_team_title',
                    'label' => 'Team Title',
                    'name' => 'about_team_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_about_team_intro',
                    'label' => 'Team Intro',
                    'name' => 'about_team_intro',
                    'type' => 'textarea',
                    'rows' => 4,
                    'new_lines' => 'br',
                ],
                [
                    'key' => 'field_about_team_members',
                    'label' => 'Team Members',
                    'name' => 'about_team_members',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Team Member',
                    'sub_fields' => [
                        [
                            'key' => 'field_about_team_member_image',
                            'label' => 'Image',
                            'name' => 'image',
                            'type' => 'image',
                            'return_format' => 'id',
                            'preview_size' => 'medium',
                            'library' => 'all',
                        ],
                        [
                            'key' => 'field_about_team_member_name',
                            'label' => 'Name',
                            'name' => 'name',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_about_team_member_position',
                            'label' => 'Position',
                            'name' => 'position',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_about_team_member_bio',
                            'label' => 'Bio',
                            'name' => 'bio',
                            'type' => 'wysiwyg',
                            'tabs' => 'all',
                            'toolbar' => 'basic',
                            'media_upload' => 0,
                        ],
                    ],
                ],
                [
                    'key' => 'field_about_page_reviews_tab',
                    'label' => 'About Reviews Section',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_reviews_title',
                    'label' => 'Reviews Title',
                    'name' => 'about_reviews_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_about_reviews_items',
                    'label' => 'Reviews Items',
                    'name' => 'about_reviews_items',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Review',
                    'sub_fields' => [
                        [
                            'key' => 'field_about_reviews_rating',
                            'label' => 'Rating',
                            'name' => 'rating',
                            'type' => 'number',
                            'min' => 1,
                            'max' => 5,
                            'step' => 1,
                        ],
                        [
                            'key' => 'field_about_reviews_text',
                            'label' => 'Text',
                            'name' => 'text',
                            'type' => 'textarea',
                            'rows' => 4,
                            'new_lines' => 'br',
                        ],
                        [
                            'key' => 'field_about_reviews_author',
                            'label' => 'Author',
                            'name' => 'author',
                            'type' => 'text',
                        ],
                    ],
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'about-template.blade.php',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ]);

        \acf_add_local_field_group([
            'key' => 'group_service_page',
            'title' => 'Service Page',
            'fields' => [
                [
                    'key' => 'field_service_page_hero_tab',
                    'label' => 'Hero / Intro Section',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_service_breadcrumb_items',
                    'label' => 'Breadcrumb Items',
                    'name' => 'service_breadcrumb_items',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Breadcrumb',
                    'sub_fields' => [
                        [
                            'key' => 'field_service_breadcrumb_item_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_service_breadcrumb_item_link',
                            'label' => 'Link',
                            'name' => 'link',
                            'type' => 'link',
                            'return_format' => 'array',
                        ],
                    ],
                ],
                [
                    'key' => 'field_service_number',
                    'label' => 'Service Number',
                    'name' => 'service_number',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_service_title',
                    'label' => 'Service Title',
                    'name' => 'service_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_service_intro',
                    'label' => 'Service Intro',
                    'name' => 'service_intro',
                    'type' => 'textarea',
                    'rows' => 4,
                    'new_lines' => 'br',
                ],
                [
                    'key' => 'field_service_items',
                    'label' => 'Service Items',
                    'name' => 'service_items',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Service Item',
                    'sub_fields' => [
                        [
                            'key' => 'field_service_item_title',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_service_item_text',
                            'label' => 'Text',
                            'name' => 'text',
                            'type' => 'textarea',
                            'rows' => 4,
                            'new_lines' => 'br',
                        ],
                    ],
                ],
                [
                    'key' => 'field_service_image',
                    'label' => 'Service Image',
                    'name' => 'service_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
                [
                    'key' => 'field_service_page_faq_tab',
                    'label' => 'Service FAQ Section',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_service_faq_title',
                    'label' => 'FAQ Title',
                    'name' => 'service_faq_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_service_faq_items',
                    'label' => 'FAQ Items',
                    'name' => 'service_faq_items',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add FAQ Item',
                    'sub_fields' => [
                        [
                            'key' => 'field_service_faq_question',
                            'label' => 'Question',
                            'name' => 'question',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_service_faq_answer',
                            'label' => 'Answer',
                            'name' => 'answer',
                            'type' => 'wysiwyg',
                            'tabs' => 'all',
                            'toolbar' => 'basic',
                            'media_upload' => 0,
                        ],
                    ],
                ],
                [
                    'key' => 'field_service_faq_button_label',
                    'label' => 'FAQ Button Label',
                    'name' => 'service_faq_button_label',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_service_faq_button_link',
                    'label' => 'FAQ Button Link',
                    'name' => 'service_faq_button_link',
                    'type' => 'link',
                    'return_format' => 'array',
                ],
                [
                    'key' => 'field_service_faq_image',
                    'label' => 'FAQ Image',
                    'name' => 'service_faq_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'service-tamplate.blade.php',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ]);

        \acf_add_local_field_group([
            'key' => 'group_blog_page',
            'title' => 'Blog Page',
            'fields' => [
                [
                    'key' => 'field_blog_page_header_tab',
                    'label' => 'Header / Breadcrumbs',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_blog_breadcrumb_items',
                    'label' => 'Breadcrumb Items',
                    'name' => 'blog_breadcrumb_items',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Breadcrumb',
                    'sub_fields' => [
                        [
                            'key' => 'field_blog_breadcrumb_item_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_blog_breadcrumb_item_link',
                            'label' => 'Link',
                            'name' => 'link',
                            'type' => 'link',
                            'return_format' => 'array',
                        ],
                    ],
                ],
                [
                    'key' => 'field_blog_title',
                    'label' => 'Title',
                    'name' => 'blog_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_blog_page_listing_tab',
                    'label' => 'Listing',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_blog_posts_per_page',
                    'label' => 'Posts Per Page',
                    'name' => 'blog_posts_per_page',
                    'type' => 'number',
                    'min' => 1,
                    'step' => 1,
                    'default_value' => 6,
                ],
                [
                    'key' => 'field_blog_read_more_label',
                    'label' => 'Read More Label',
                    'name' => 'blog_read_more_label',
                    'type' => 'text',
                    'default_value' => 'Czytaj więcej',
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'blog-template.blade.php',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ]);

        \acf_add_local_field_group([
            'key' => 'group_single_post_settings',
            'title' => 'Single Post Settings',
            'fields' => [
                [
                    'key' => 'field_single_post_content_tab',
                    'label' => 'Post Content',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_single_post_breadcrumb_items',
                    'label' => 'Breadcrumb Items',
                    'name' => 'single_post_breadcrumb_items',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Breadcrumb',
                    'sub_fields' => [
                        [
                            'key' => 'field_single_post_breadcrumb_item_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_single_post_breadcrumb_item_link',
                            'label' => 'Link',
                            'name' => 'link',
                            'type' => 'link',
                            'return_format' => 'array',
                        ],
                    ],
                ],
                [
                    'key' => 'field_single_post_title',
                    'label' => 'Title',
                    'name' => 'single_post_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_single_post_content',
                    'label' => 'Content',
                    'name' => 'single_post_content',
                    'type' => 'wysiwyg',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                ],
                [
                    'key' => 'field_single_post_summary',
                    'label' => 'Summary',
                    'name' => 'single_post_summary',
                    'type' => 'textarea',
                    'rows' => 4,
                ],
                [
                    'key' => 'field_single_post_hero_image',
                    'label' => 'Hero Image',
                    'name' => 'single_post_hero_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
                [
                    'key' => 'field_single_post_thumbnail_image',
                    'label' => 'Thumbnail Image',
                    'name' => 'single_post_thumbnail_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
                [
                    'key' => 'field_single_post_navigation_tab',
                    'label' => 'Navigation',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_single_post_navigation_enabled',
                    'label' => 'Navigation Enabled',
                    'name' => 'single_post_navigation_enabled',
                    'type' => 'true_false',
                    'ui' => 1,
                    'default_value' => 1,
                ],
                [
                    'key' => 'field_single_post_previous_label',
                    'label' => 'Previous Label',
                    'name' => 'single_post_previous_label',
                    'type' => 'text',
                    'default_value' => 'Poprzedni post',
                ],
                [
                    'key' => 'field_single_post_read_more_label',
                    'label' => 'Read More Label',
                    'name' => 'single_post_read_more_label',
                    'type' => 'text',
                    'default_value' => 'Czytaj więcej',
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'post',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ]);

        \acf_add_local_field_group([
            'key' => 'group_contact_page',
            'title' => 'Contact Page',
            'fields' => [
                [
                    'key' => 'field_contact_page_header_tab',
                    'label' => 'Header',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_contact_breadcrumb_items',
                    'label' => 'Breadcrumb Items',
                    'name' => 'contact_breadcrumb_items',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Breadcrumb',
                    'sub_fields' => [
                        [
                            'key' => 'field_contact_breadcrumb_item_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_contact_breadcrumb_item_link',
                            'label' => 'Link',
                            'name' => 'link',
                            'type' => 'link',
                            'return_format' => 'array',
                        ],
                    ],
                ],
                [
                    'key' => 'field_contact_title',
                    'label' => 'Title',
                    'name' => 'contact_title',
                    'type' => 'text',
                    'default_value' => 'Kontakt',
                ],
                [
                    'key' => 'field_contact_page_details_tab',
                    'label' => 'Contact Details',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_contact_details_heading',
                    'label' => 'Details Heading',
                    'name' => 'contact_details_heading',
                    'type' => 'text',
                    'default_value' => 'Kontakt',
                ],
                [
                    'key' => 'field_contact_details_rows',
                    'label' => 'Details Rows',
                    'name' => 'contact_details_rows',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Detail Row',
                    'sub_fields' => [
                        [
                            'key' => 'field_contact_details_row_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_contact_details_row_value',
                            'label' => 'Value',
                            'name' => 'value',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_contact_details_row_type',
                            'label' => 'Type',
                            'name' => 'type',
                            'type' => 'select',
                            'choices' => [
                                'text' => 'Text',
                                'phone' => 'Phone',
                                'email' => 'Email',
                                'address' => 'Address',
                            ],
                            'default_value' => 'text',
                            'return_format' => 'value',
                            'ui' => 1,
                        ],
                    ],
                ],
                [
                    'key' => 'field_contact_page_socials_tab',
                    'label' => 'Socials',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_contact_socials',
                    'label' => 'Social Links',
                    'name' => 'contact_socials',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Social Link',
                    'sub_fields' => [
                        [
                            'key' => 'field_contact_social_icon',
                            'label' => 'Icon',
                            'name' => 'icon',
                            'type' => 'font-awesome',
                            'instructions' => 'Enter Font Awesome classes, for example fa-brands fa-facebook-f.',
                            'default_value' => 'fa-brands fa-facebook-f',
                        ],
                        [
                            'key' => 'field_contact_social_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_contact_social_url',
                            'label' => 'URL',
                            'name' => 'url',
                            'type' => 'url',
                        ],
                    ],
                ],
                [
                    'key' => 'field_contact_page_form_tab',
                    'label' => 'Form',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_contact_form_heading',
                    'label' => 'Form Heading',
                    'name' => 'contact_form_heading',
                    'type' => 'text',
                    'default_value' => 'Zostaw wiadomość',
                ],
                [
                    'key' => 'field_contact_form_shortcode_pl',
                    'label' => 'Form Shortcode (PL)',
                    'name' => 'contact_form_shortcode_pl',
                    'type' => 'textarea',
                    'rows' => 4,
                    'new_lines' => '',
                ],
                [
                    'key' => 'field_contact_form_shortcode_en',
                    'label' => 'Form Shortcode (EN)',
                    'name' => 'contact_form_shortcode_en',
                    'type' => 'textarea',
                    'rows' => 4,
                    'new_lines' => '',
                ],
                [
                    'key' => 'field_contact_form_shortcode_fr',
                    'label' => 'Form Shortcode (FR)',
                    'name' => 'contact_form_shortcode_fr',
                    'type' => 'textarea',
                    'rows' => 4,
                    'new_lines' => '',
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'template-contact.blade.php',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ]);

        \acf_add_local_field_group([
            'key' => 'group_privacy_page',
            'title' => 'Privacy Policy Page',
            'fields' => [
                [
                    'key' => 'field_privacy_policy_content',
                    'label' => 'Privacy Policy Content',
                    'name' => 'privacy_policy_content',
                    'type' => 'wysiwyg',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'template-privacy-policy.blade.php',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ]);

        \acf_add_local_field_group([
            'key' => 'group_header_footer_settings',
            'title' => 'Header/Footer Settings',
            'fields' => [
                [
                    'key' => 'field_header_page_tab',
                    'label' => 'Header',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_header_logo_text',
                    'label' => 'Logo Text',
                    'name' => 'header_logo_text',
                    'type' => 'text',
                    'default_value' => 'Ewa Kodymowska-Sioła',
                ],
                [
                    'key' => 'field_header_logo_link',
                    'label' => 'Logo Link',
                    'name' => 'header_logo_link',
                    'type' => 'link',
                    'return_format' => 'array',
                ],
                [
                    'key' => 'field_header_show_language_switcher',
                    'label' => 'Show Language Switcher',
                    'name' => 'header_show_language_switcher',
                    'type' => 'true_false',
                    'ui' => 1,
                    'default_value' => 1,
                ],
                [
                    'key' => 'field_global_menu_open_label',
                    'label' => 'Menu Open Label',
                    'name' => 'global_menu_open_label',
                    'type' => 'text',
                    'default_value' => 'Menu',
                ],
                [
                    'key' => 'field_global_menu_close_label',
                    'label' => 'Menu Close Label',
                    'name' => 'global_menu_close_label',
                    'type' => 'text',
                    'default_value' => 'Zamknij',
                ],
                [
                    'key' => 'field_footer_page_tab',
                    'label' => 'Footer',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_footer_cta_image',
                    'label' => 'CTA Image',
                    'name' => 'footer_cta_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
                [
                    'key' => 'field_footer_cta_title',
                    'label' => 'CTA Title',
                    'name' => 'footer_cta_title',
                    'type' => 'textarea',
                    'rows' => 3,
                    'new_lines' => 'br',
                ],
                [
                    'key' => 'field_footer_cta_button_label',
                    'label' => 'CTA Button Label',
                    'name' => 'footer_cta_button_label',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_footer_cta_button_link',
                    'label' => 'CTA Button Link',
                    'name' => 'footer_cta_button_link',
                    'type' => 'link',
                    'return_format' => 'array',
                ],
                [
                    'key' => 'field_footer_name',
                    'label' => 'Name',
                    'name' => 'footer_name',
                    'type' => 'text',
                    'default_value' => 'Ewa Kodymowska-Sioła',
                ],
                [
                    'key' => 'field_footer_socials',
                    'label' => 'Socials',
                    'name' => 'footer_socials',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Social Link',
                    'sub_fields' => [
                        [
                            'key' => 'field_footer_social_icon',
                            'label' => 'Icon',
                            'name' => 'icon',
                            'type' => 'font-awesome',
                            'instructions' => 'Enter Font Awesome classes, for example fa-brands fa-facebook-f.',
                            'default_value' => 'fa-brands fa-facebook-f',
                        ],
                        [
                            'key' => 'field_footer_social_url',
                            'label' => 'URL',
                            'name' => 'url',
                            'type' => 'url',
                        ],
                    ],
                ],
                [
                    'key' => 'field_footer_privacy_label',
                    'label' => 'Privacy Label',
                    'name' => 'footer_privacy_label',
                    'type' => 'text',
                    'default_value' => 'Polityka Prywatności',
                ],
                [
                    'key' => 'field_footer_privacy_link',
                    'label' => 'Privacy Link',
                    'name' => 'footer_privacy_link',
                    'type' => 'link',
                    'return_format' => 'array',
                ],
                [
                    'key' => 'field_footer_copyright_text',
                    'label' => 'Copyright Text',
                    'name' => 'footer_copyright_text',
                    'type' => 'textarea',
                    'rows' => 3,
                    'new_lines' => 'br',
                ],
                [
                    'key' => 'field_footer_copyright_heart_symbol',
                    'label' => 'Copyright Heart Symbol',
                    'name' => 'footer_copyright_heart_symbol',
                    'type' => 'text',
                    'default_value' => '♥',
                ],
                [
                    'key' => 'field_footer_copyright_agency_text',
                    'label' => 'Copyright Agency Text',
                    'name' => 'footer_copyright_agency_text',
                    'type' => 'text',
                    'default_value' => 'SLT Media',
                ],
                [
                    'key' => 'field_footer_services_heading',
                    'label' => 'Services Heading',
                    'name' => 'footer_services_heading',
                    'type' => 'text',
                    'default_value' => 'Usługi',
                ],
                [
                    'key' => 'field_footer_services',
                    'label' => 'Services',
                    'name' => 'footer_services',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Service Link',
                    'sub_fields' => [
                        [
                            'key' => 'field_footer_service_title',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_footer_service_link',
                            'label' => 'Link',
                            'name' => 'link',
                            'type' => 'link',
                            'return_format' => 'array',
                        ],
                    ],
                ],
                [
                    'key' => 'field_footer_contact_heading',
                    'label' => 'Contact Heading',
                    'name' => 'footer_contact_heading',
                    'type' => 'text',
                    'default_value' => 'Kontakt',
                ],
                [
                    'key' => 'field_footer_contact_rows',
                    'label' => 'Contact Rows',
                    'name' => 'footer_contact_rows',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Contact Row',
                    'sub_fields' => [
                        [
                            'key' => 'field_footer_contact_row_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_footer_contact_row_value',
                            'label' => 'Value',
                            'name' => 'value',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_footer_contact_row_type',
                            'label' => 'Type',
                            'name' => 'type',
                            'type' => 'select',
                            'choices' => [
                                'text' => 'Text',
                                'phone' => 'Phone',
                                'email' => 'Email',
                                'address' => 'Address',
                            ],
                            'default_value' => 'text',
                            'return_format' => 'value',
                            'ui' => 1,
                        ],
                    ],
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'header-footer-pl',
                    ],
                ],
                [
                    [
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'header-footer-en',
                    ],
                ],
                [
                    [
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'header-footer-fr',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ]);
    }
}
