<?php

namespace App\Providers;

class ACFFieldProvider
{
    public static function register(): void
    {
        static::registerFieldGroups();
    }

    public static function registerFieldGroups(): void
    {
        if (! \function_exists('acf_add_local_field_group')) {
            return;
        }

        \acf_add_local_field_group([
            'key' => 'group_front_page',
            'title' => 'Front Page',
            'fields' => [
                [
                    'key' => 'field_front_page_hero_tab',
                    'label' => 'Hero',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_front_hero_background_image',
                    'label' => 'Hero Background Image',
                    'name' => 'front_hero_background_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
                [
                    'key' => 'field_front_hero_arrow_text',
                    'label' => 'Hero Arrow Text',
                    'name' => 'front_hero_arrow_text',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_hero_eyebrow',
                    'label' => 'Hero Eyebrow',
                    'name' => 'front_hero_eyebrow',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_hero_title',
                    'label' => 'Hero Title',
                    'name' => 'front_hero_title',
                    'type' => 'textarea',
                    'rows' => 3,
                    'new_lines' => 'br',
                ],
                [
                    'key' => 'field_front_page_services_tab',
                    'label' => 'Services Navigation',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_front_services',
                    'label' => 'Services',
                    'name' => 'front_services',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Service',
                    'sub_fields' => [
                        [
                            'key' => 'field_front_services_number',
                            'label' => 'Number',
                            'name' => 'number',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_front_services_title',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_front_services_link',
                            'label' => 'Link',
                            'name' => 'link',
                            'type' => 'link',
                            'return_format' => 'array',
                        ],
                        [
                            'key' => 'field_front_services_read_more_label',
                            'label' => 'Read More Label',
                            'name' => 'read_more_label',
                            'type' => 'text',
                            'default_value' => 'Czytaj więcej',
                        ],
                    ],
                ],
                [
                    'key' => 'field_front_page_philosophy_tab',
                    'label' => 'Philosophy Teaser',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_front_philosophy_image',
                    'label' => 'Philosophy Image',
                    'name' => 'front_philosophy_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
                [
                    'key' => 'field_front_philosophy_arrow_text',
                    'label' => 'Philosophy Arrow Text',
                    'name' => 'front_philosophy_arrow_text',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_philosophy_title',
                    'label' => 'Philosophy Title',
                    'name' => 'front_philosophy_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_philosophy_text',
                    'label' => 'Philosophy Text',
                    'name' => 'front_philosophy_text',
                    'type' => 'wysiwyg',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                ],
                [
                    'key' => 'field_front_philosophy_button_label',
                    'label' => 'Philosophy Button Label',
                    'name' => 'front_philosophy_button_label',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_philosophy_button_link',
                    'label' => 'Philosophy Button Link',
                    'name' => 'front_philosophy_button_link',
                    'type' => 'link',
                    'return_format' => 'array',
                ],
                [
                    'key' => 'field_front_page_team_tab',
                    'label' => 'Team Teaser',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_front_team_title',
                    'label' => 'Team Title',
                    'name' => 'front_team_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_team_description',
                    'label' => 'Team Description',
                    'name' => 'front_team_description',
                    'type' => 'textarea',
                    'rows' => 4,
                    'new_lines' => 'br',
                ],
                [
                    'key' => 'field_front_team_button_label',
                    'label' => 'Team Button Label',
                    'name' => 'front_team_button_label',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_team_button_link',
                    'label' => 'Team Button Link',
                    'name' => 'front_team_button_link',
                    'type' => 'link',
                    'return_format' => 'array',
                ],
                [
                    'key' => 'field_front_team_featured_image',
                    'label' => 'Featured Team Image',
                    'name' => 'front_team_featured_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
                [
                    'key' => 'field_front_team_featured_name',
                    'label' => 'Featured Team Name',
                    'name' => 'front_team_featured_name',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_team_featured_position',
                    'label' => 'Featured Team Position',
                    'name' => 'front_team_featured_position',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_team_featured_description',
                    'label' => 'Featured Team Description',
                    'name' => 'front_team_featured_description',
                    'type' => 'textarea',
                    'rows' => 5,
                    'new_lines' => 'br',
                ],
                [
                    'key' => 'field_front_page_reviews_tab',
                    'label' => 'Google Reviews Teaser',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_front_reviews_title',
                    'label' => 'Reviews Title',
                    'name' => 'front_reviews_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_reviews_items',
                    'label' => 'Reviews',
                    'name' => 'front_reviews_items',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Review',
                    'sub_fields' => [
                        [
                            'key' => 'field_front_reviews_rating',
                            'label' => 'Rating',
                            'name' => 'rating',
                            'type' => 'number',
                            'min' => 1,
                            'max' => 5,
                            'step' => 1,
                        ],
                        [
                            'key' => 'field_front_reviews_text',
                            'label' => 'Text',
                            'name' => 'text',
                            'type' => 'textarea',
                            'rows' => 4,
                            'new_lines' => 'br',
                        ],
                        [
                            'key' => 'field_front_reviews_author',
                            'label' => 'Author',
                            'name' => 'author',
                            'type' => 'text',
                        ],
                    ],
                ],
                [
                    'key' => 'field_front_page_faq_tab',
                    'label' => 'FAQ Teaser',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_front_faq_title',
                    'label' => 'FAQ Title',
                    'name' => 'front_faq_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_faq_items',
                    'label' => 'FAQ Items',
                    'name' => 'front_faq_items',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add FAQ Item',
                    'sub_fields' => [
                        [
                            'key' => 'field_front_faq_question',
                            'label' => 'Question',
                            'name' => 'question',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_front_faq_answer',
                            'label' => 'Answer',
                            'name' => 'answer',
                            'type' => 'wysiwyg',
                            'tabs' => 'all',
                            'toolbar' => 'basic',
                            'media_upload' => 0,
                        ],
                    ],
                ],
                [
                    'key' => 'field_front_faq_button_label',
                    'label' => 'FAQ Button Label',
                    'name' => 'front_faq_button_label',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_front_faq_button_link',
                    'label' => 'FAQ Button Link',
                    'name' => 'front_faq_button_link',
                    'type' => 'link',
                    'return_format' => 'array',
                ],
                [
                    'key' => 'field_front_faq_image',
                    'label' => 'FAQ Image',
                    'name' => 'front_faq_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'page_type',
                        'operator' => '==',
                        'value' => 'front_page',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ]);

        \acf_add_local_field_group([
            'key' => 'group_about_us_page',
            'title' => 'About Us Page',
            'fields' => [
                [
                    'key' => 'field_about_page_breadcrumbs_tab',
                    'label' => 'Breadcrumbs',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_breadcrumb_current_label',
                    'label' => 'Current Label',
                    'name' => 'about_breadcrumb_current_label',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_about_page_philosophy_tab',
                    'label' => 'Philosophy Section',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_philosophy_title',
                    'label' => 'Philosophy Title',
                    'name' => 'about_philosophy_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_about_philosophy_content',
                    'label' => 'Philosophy Content',
                    'name' => 'about_philosophy_content',
                    'type' => 'wysiwyg',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                ],
                [
                    'key' => 'field_about_philosophy_image',
                    'label' => 'Philosophy Image',
                    'name' => 'about_philosophy_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
                [
                    'key' => 'field_about_page_why_tab',
                    'label' => 'Why Us Section',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_why_image',
                    'label' => 'Why Us Image',
                    'name' => 'about_why_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
                [
                    'key' => 'field_about_why_title',
                    'label' => 'Why Us Title',
                    'name' => 'about_why_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_about_why_content',
                    'label' => 'Why Us Content',
                    'name' => 'about_why_content',
                    'type' => 'wysiwyg',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                ],
                [
                    'key' => 'field_about_page_team_tab',
                    'label' => 'Team Section',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_team_title',
                    'label' => 'Team Title',
                    'name' => 'about_team_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_about_team_intro',
                    'label' => 'Team Intro',
                    'name' => 'about_team_intro',
                    'type' => 'textarea',
                    'rows' => 4,
                    'new_lines' => 'br',
                ],
                [
                    'key' => 'field_about_team_members',
                    'label' => 'Team Members',
                    'name' => 'about_team_members',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Team Member',
                    'sub_fields' => [
                        [
                            'key' => 'field_about_team_member_image',
                            'label' => 'Image',
                            'name' => 'image',
                            'type' => 'image',
                            'return_format' => 'id',
                            'preview_size' => 'medium',
                            'library' => 'all',
                        ],
                        [
                            'key' => 'field_about_team_member_name',
                            'label' => 'Name',
                            'name' => 'name',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_about_team_member_position',
                            'label' => 'Position',
                            'name' => 'position',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_about_team_member_bio',
                            'label' => 'Bio',
                            'name' => 'bio',
                            'type' => 'wysiwyg',
                            'tabs' => 'all',
                            'toolbar' => 'basic',
                            'media_upload' => 0,
                        ],
                    ],
                ],
                [
                    'key' => 'field_about_page_reviews_tab',
                    'label' => 'About Reviews Section',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_reviews_title',
                    'label' => 'Reviews Title',
                    'name' => 'about_reviews_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_about_reviews_items',
                    'label' => 'Reviews Items',
                    'name' => 'about_reviews_items',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Review',
                    'sub_fields' => [
                        [
                            'key' => 'field_about_reviews_rating',
                            'label' => 'Rating',
                            'name' => 'rating',
                            'type' => 'number',
                            'min' => 1,
                            'max' => 5,
                            'step' => 1,
                        ],
                        [
                            'key' => 'field_about_reviews_text',
                            'label' => 'Text',
                            'name' => 'text',
                            'type' => 'textarea',
                            'rows' => 4,
                            'new_lines' => 'br',
                        ],
                        [
                            'key' => 'field_about_reviews_author',
                            'label' => 'Author',
                            'name' => 'author',
                            'type' => 'text',
                        ],
                    ],
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'about-template.blade.php',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ]);

        \acf_add_local_field_group([
            'key' => 'group_service_page',
            'title' => 'Service Page',
            'fields' => [
                [
                    'key' => 'field_service_page_hero_tab',
                    'label' => 'Hero / Intro Section',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_service_breadcrumb_parent_label',
                    'label' => 'Breadcrumb Parent Label',
                    'name' => 'service_breadcrumb_parent_label',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_service_breadcrumb_parent_link',
                    'label' => 'Breadcrumb Parent Link',
                    'name' => 'service_breadcrumb_parent_link',
                    'type' => 'link',
                    'return_format' => 'array',
                ],
                [
                    'key' => 'field_service_breadcrumb_current_label',
                    'label' => 'Breadcrumb Current Label',
                    'name' => 'service_breadcrumb_current_label',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_service_number',
                    'label' => 'Service Number',
                    'name' => 'service_number',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_service_title',
                    'label' => 'Service Title',
                    'name' => 'service_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_service_items',
                    'label' => 'Service Items',
                    'name' => 'service_items',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add Service Item',
                    'sub_fields' => [
                        [
                            'key' => 'field_service_item_title',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_service_item_text',
                            'label' => 'Text',
                            'name' => 'text',
                            'type' => 'textarea',
                            'rows' => 4,
                            'new_lines' => 'br',
                        ],
                    ],
                ],
                [
                    'key' => 'field_service_image',
                    'label' => 'Service Image',
                    'name' => 'service_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
                [
                    'key' => 'field_service_page_faq_tab',
                    'label' => 'Service FAQ Section',
                    'name' => '',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_service_faq_title',
                    'label' => 'FAQ Title',
                    'name' => 'service_faq_title',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_service_faq_items',
                    'label' => 'FAQ Items',
                    'name' => 'service_faq_items',
                    'type' => 'repeater',
                    'layout' => 'row',
                    'button_label' => 'Add FAQ Item',
                    'sub_fields' => [
                        [
                            'key' => 'field_service_faq_question',
                            'label' => 'Question',
                            'name' => 'question',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_service_faq_answer',
                            'label' => 'Answer',
                            'name' => 'answer',
                            'type' => 'wysiwyg',
                            'tabs' => 'all',
                            'toolbar' => 'basic',
                            'media_upload' => 0,
                        ],
                    ],
                ],
                [
                    'key' => 'field_service_faq_button_label',
                    'label' => 'FAQ Button Label',
                    'name' => 'service_faq_button_label',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_service_faq_button_link',
                    'label' => 'FAQ Button Link',
                    'name' => 'service_faq_button_link',
                    'type' => 'link',
                    'return_format' => 'array',
                ],
                [
                    'key' => 'field_service_faq_image',
                    'label' => 'FAQ Image',
                    'name' => 'service_faq_image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'service-tamplate.blade.php',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ]);
    }
}
